//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace moonlight
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skins
    {
        public string SkinName { get; set; }
        public string ChampionName { get; set; }
    
        public virtual Champions Champions { get; set; }
    }
}
